### ISSUE TITLE
Old vignette still available in website

### ISSUE THREAD

**Issue by peterdesmet** [inbo/inlatools#6]
I notice `dispersion.Rmd` has been removed in https://github.com/inbo/inlatools/commit/7536366e0f37598820a5dd2d62fca008a105cde7#diff-01930b8536a636ea3cd8940e4333b78d16f0eb821a0c60f7c6f59a9eb9749009

It is still available on the website: https://inlatools.netlify.app/articles/dispersion.html

**Comment by peterdesmet** [comment]
Correction: dispersion, not distribution

**Comment by ThierryO** [comment]
The new pkgdown website is online: https://inbo.github.io/inlatools/
